(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ca(this);function da(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
da("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.g=e;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d=0;return b});
da("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return a});function ea(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function q(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function fa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ha(){this.m=!1;this.j=null;this.s=void 0;this.g=1;this.l=this.i=0;this.o=this.h=null}function ia(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}f=ha.prototype;f.I=function(a){this.s=a};function ja(a,b){a.h={T:b,U:!0};a.g=a.i||a.l}
f.return=function(a){this.h={return:a};this.g=this.l};f.bb=function(a){this.h={C:a};this.g=this.l};function r(a,b,c){a.g=c;return{value:b}}f.Xc=function(a,b){a=q(a);var c=a.next();fa(c);if(c.done)this.s=c.value,this.g=b;else return this.j=a,r(this,c.value,b)};f.C=function(a){this.g=a};f.cb=function(){this.g=0};f.xb=function(a){this.i=0;this.l=a||0};function ka(a,b){a.g=b;a.i=0}function la(a){a.i=0;var b=a.h.T;a.h=null;return b}
f.ma=function(a,b,c){c?this.o[c]=this.h:this.o=[this.h];this.i=a||0;this.l=b||0};f.eb=function(a,b){b=this.o.splice(b||0)[0];(b=this.h=this.h||b)?b.U?this.g=this.i||this.l:void 0!=b.C&&this.l<b.C?(this.g=b.C,this.h=null):this.g=this.l:this.g=a};f.qa=function(a){return new ma(a)};function ma(a){this.h=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}ma.prototype.i=function(){for(;0<this.g.length;){var a=this.g.pop();if(a in this.h)return a}return null};
function na(a){this.g=new ha;this.h=a}function oa(a,b){ia(a.g);var c=a.g.j;if(c)return pa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return qa(a)}function pa(a,b,c,d){try{var e=b.call(a.g.j,c);fa(e);if(!e.done)return a.g.m=!1,e;var g=e.value}catch(h){return a.g.j=null,ja(a.g,h),qa(a)}a.g.j=null;d.call(a.g,g);return qa(a)}
function qa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.s=void 0,ja(a.g,c)}a.g.m=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.U)throw b.T;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ra(a){this.next=function(b){ia(a.g);a.g.j?b=pa(a,a.g.j.next,b,a.g.I):(a.g.I(b),b=qa(a));return b};this.throw=function(b){ia(a.g);a.g.j?b=pa(a,a.g.j["throw"],b,a.g.I):(ja(a.g,b),b=qa(a));return b};this.return=function(b){return oa(a,b)};this[Symbol.iterator]=function(){return this}}function sa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
da("Promise",function(a){function b(h){this.h=0;this.i=void 0;this.g=[];this.o=!1;var k=this.j();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.g=null}function d(h){return h instanceof b?h:new b(function(k){k(h)})}if(a)return a;c.prototype.h=function(h){if(null==this.g){this.g=[];var k=this;this.i(function(){k.l()})}this.g.push(h)};var e=n.setTimeout;c.prototype.i=function(h){e(h,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var h=this.g;this.g=[];for(var k=0;k<h.length;++k){var l=
h[k];h[k]=null;try{l()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(h){this.i(function(){throw h;})};b.prototype.j=function(){function h(m){return function(p){l||(l=!0,m.call(k,p))}}var k=this,l=!1;return{resolve:h(this.K),reject:h(this.l)}};b.prototype.K=function(h){if(h===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.W(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.J(h):this.m(h)}};
b.prototype.J=function(h){var k=void 0;try{k=h.then}catch(l){this.l(l);return}"function"==typeof k?this.X(k,h):this.m(h)};b.prototype.l=function(h){this.s(2,h)};b.prototype.m=function(h){this.s(1,h)};b.prototype.s=function(h,k){if(0!=this.h)throw Error("Cannot settle("+h+", "+k+"): Promise already settled in state"+this.h);this.h=h;this.i=k;2===this.h&&this.S();this.D()};b.prototype.S=function(){var h=this;e(function(){if(h.R()){var k=n.console;"undefined"!==typeof k&&k.error(h.i)}},1)};b.prototype.R=
function(){if(this.o)return!1;var h=n.CustomEvent,k=n.Event,l=n.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=n.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.i;return l(h)};b.prototype.D=function(){if(null!=this.g){for(var h=0;h<this.g.length;++h)g.h(this.g[h]);this.g=null}};var g=new c;b.prototype.W=
function(h){var k=this.j();h.H(k.resolve,k.reject)};b.prototype.X=function(h,k){var l=this.j();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(h,k){function l(J,T){return"function"==typeof J?function(Qa){try{m(J(Qa))}catch(Ra){p(Ra)}}:T}var m,p,I=new b(function(J,T){m=J;p=T});this.H(l(h,m),l(k,p));return I};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.H=function(h,k){function l(){switch(m.h){case 1:h(m.i);break;case 2:k(m.i);break;default:throw Error("Unexpected state: "+
m.h);}}var m=this;null==this.g?g.h(l):this.g.push(l);this.o=!0};b.resolve=d;b.reject=function(h){return new b(function(k,l){l(h)})};b.race=function(h){return new b(function(k,l){for(var m=q(h),p=m.next();!p.done;p=m.next())d(p.value).H(k,l)})};b.all=function(h){var k=q(h),l=k.next();return l.done?d([]):new b(function(m,p){function I(Qa){return function(Ra){J[Qa]=Ra;T--;0==T&&m(J)}}var J=[],T=0;do J.push(void 0),T++,d(l.value).H(I(J.length-1),p),l=k.next();while(!l.done)})};return b});
function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
da("WeakMap",function(a){function b(l){this.g=(k+=Math.random()+1).toString();if(l){l=q(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,h)){var m=new c;ba(l,h,{value:m})}}function g(l){var m=Object[l];m&&(Object[l]=function(p){if(p instanceof c)return p;Object.isExtensible(p)&&e(p);return m(p)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),
p=new a([[l,2],[m,3]]);if(2!=p.get(l)||3!=p.get(m))return!1;p.delete(l);p.set(m,4);return!p.has(l)&&4==p.get(m)}catch(I){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,h))throw Error("WeakMap key fail: "+l);l[h][this.g]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,h)?l[h][this.g]:void 0};b.prototype.has=function(l){return d(l)&&t(l,
h)&&t(l[h],this.g)};b.prototype.delete=function(l){return d(l)&&t(l,h)&&t(l[h],this.g)?delete l[h][this.g]:!1};return b});
da("Map",function(a){function b(){var k={};return k.A=k.next=k.head=k}function c(k,l){var m=k.g;return ea(function(){if(m){for(;m.head!=k.g;)m=m.A;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?g.has(l)?m=g.get(l):(m=""+ ++h,g.set(l,m)):m="p_"+l;var p=k.h[m];if(p&&t(k.h,m))for(k=0;k<p.length;k++){var I=p[k];if(l!==l&&I.key!==I.key||l===I.key)return{id:m,list:p,index:k,u:I}}return{id:m,list:p,
index:-1,u:void 0}}function e(k){this.h={};this.g=b();this.size=0;if(k){k=q(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(q([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),p=m.next();if(p.done||p.value[0]!=k||"s"!=p.value[1])return!1;p=m.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!m.next().done?!1:!0}catch(I){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.h[m.id]=[]);m.u?m.u.value=l:(m.u={next:this.g,A:this.g.A,head:this.g,key:k,value:l},m.list.push(m.u),this.g.A.next=m.u,this.g.A=m.u,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.u&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.h[k.id],k.u.A.next=k.u.next,k.u.next.A=k.u.A,k.u.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.A=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).u};e.prototype.get=function(k){return(k=d(this,k).u)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),p;!(p=m.next()).done;)p=p.value,
k.call(l,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});var u=this||self,ta=/^[\w+/_-]+[=]{0,2}$/,ua=null;function va(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ta.test(a)?a:""}function wa(){}function xa(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function ya(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function za(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function v(a,b){a=a.split(".");var c=u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function Aa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.da=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}}function Ba(a){return a};var w=new Map([]);w.set("devsite-a11y-announce",{src:"/js/devsite_devsite_a11y_announce_module.js"});w.set("devsite-analytics",{src:"/js/devsite_devsite_analytics_module.js"});w.set("devsite-analytics-scope",{src:"/js/devsite_devsite_analytics_scope_module.js"});w.set("devsite-anselm",{src:"/js/devsite_devsite_anselm_module.js"});w.set("devsite-api-getstarted",{src:"/js/devsite_devsite_api_getstarted_module.js"});w.set("devsite-apix",{src:"/js/devsite_devsite_apix_module.js"});
w.set("devsite-apix-index",{src:"/js/devsite_devsite_apix_index_module.js"});w.set("devsite-apix-snippets",{src:"/js/devsite_devsite_apix_snippets_module.js"});w.set("devsite-badger",{src:"/js/devsite_devsite_badger_module.js"});w.set("devsite-badge-awarded",{src:"/js/devsite_devsite_badge_awarded_module.js"});w.set("devsite-badge-awarder",{src:"/js/devsite_devsite_badge_awarder_module.js"});w.set("devsite-badge-redeemer",{src:"/js/devsite_devsite_badge_redeemer_module.js"});
w.set("devsite-book-nav",{src:"/js/devsite_devsite_book_nav_module.js"});w.set("devsite-chart",{src:"/js/devsite_devsite_chart_module.js"});w.set("devsite-code",{src:"/js/devsite_devsite_code_module.js"});w.set("devsite-content",{src:"/js/devsite_devsite_content_module.js"});w.set("devsite-catalog",{src:"/js/devsite_devsite_catalog_module.js"});w.set("devsite-codelab-catalog",{src:"/js/devsite_devsite_codelab_catalog_module.js"});w.set("devsite-credentials-dialog",{src:"/js/devsite_devsite_credentials_dialog_module.js"});
w.set("devsite-cse",{src:"/js/devsite_devsite_cse_module.js"});w.set("devsite-device",{src:"/js/devsite_devsite_device_module.js"});w.set("devsite-devprofile",{src:"/js/devsite_devsite_devprofile_module.js"});w.set("devsite-dialog",{src:"/js/devsite_devsite_dialog_module.js"});w.set("devsite-dynamic-content",{src:"/js/devsite_devsite_dynamic_content_module.js"});w.set("devsite-expandable",{src:"/js/devsite_devsite_expandable_module.js"});w.set("devsite-expandable-nav",{src:"/js/devsite_devsite_expandable_nav_module.js"});
w.set("devsite-extradory",{src:"/js/devsite_devsite_extradory_module.js"});w.set("devsite-feedback",{src:"/js/devsite_devsite_feedback_module.js"});w.set("devsite-filter",{src:"/js/devsite_devsite_filter_module.js"});w.set("devsite-footer-linkboxes",{src:"/js/devsite_devsite_footer_linkboxes_module.js"});w.set("devsite-footer-promos",{src:"/js/devsite_devsite_footer_promos_module.js"});w.set("devsite-footer-utility",{src:"/js/devsite_devsite_footer_utility_module.js"});w.set("devsite-forum",{src:"/js/devsite_devsite_forum_module.js"});
w.set("devsite-google-survey",{src:"/js/devsite_devsite_google_survey_module.js"});w.set("devsite-googler-buttons",{src:"/js/devsite_devsite_googler_buttons_module.js"});w.set("devsite-hats-survey",{src:"/js/devsite_devsite_hats_survey_module.js"});w.set("devsite-header",{src:"/js/devsite_devsite_header_module.js"});w.set("devsite-heading-link",{src:"/js/devsite_devsite_heading_link_module.js"});w.set("devsite-iframe",{src:"/js/devsite_devsite_iframe_module.js"});w.set("devsite-jump-to",{src:"/js/devsite_devsite_jump_to_module.js"});
w.set("devsite-jsfiddle-button",{src:"/js/devsite_devsite_jsfiddle_button_module.js"});w.set("devsite-language-selector",{src:"/js/devsite_devsite_language_selector_module.js"});w.set("devsite-lightbox",{src:"/js/devsite_devsite_lightbox_module.js"});w.set("devsite-mathjax",{src:"/js/devsite_devsite_mathjax_module.js"});w.set("devsite-mdc",{src:"/js/devsite_devsite_mdc_module.js"});w.set("devsite-multiple-choice",{src:"/js/devsite_devsite_multiple_choice_module.js"});w.set("devsite-nav-buttons",{src:"/js/devsite_devsite_nav_buttons_module.js"});
w.set("devsite-playlist",{src:"/js/devsite_devsite_playlist_module.js"});w.set("devsite-page-rating",{src:"/js/devsite_devsite_page_rating_module.js"});w.set("devsite-pagination",{src:"/js/devsite_devsite_pagination_module.js"});w.set("devsite-progress",{src:"/js/devsite_devsite_progress_module.js"});w.set("devsite-quiz",{src:"/js/devsite_devsite_quiz_module.js"});w.set("devsite-recommendations",{src:"/js/devsite_devsite_recommendations_module.js"});w.set("devsite-reference-results",{src:"/js/devsite_devsite_reference_results_module.js"});
w.set("devsite-search",{src:"/js/devsite_devsite_search_module.js"});w.set("devsite-select",{src:"/js/devsite_devsite_select_module.js"});w.set("devsite-selector",{src:"/js/devsite_devsite_selector_module.js"});w.set("devsite-sitemask",{src:"/js/devsite_devsite_sitemask_module.js"});w.set("devsite-snackbar",{src:"/js/devsite_devsite_snackbar_module.js"});w.set("devsite-sort",{src:"/js/devsite_devsite_sort_module.js"});w.set("devsite-spinner",{src:"/js/devsite_devsite_spinner_module.js"});
w.set("devsite-support-form",{src:"/js/devsite_devsite_support_form_module.js"});w.set("devsite-tabs",{src:"/js/devsite_devsite_tabs_module.js"});w.set("devsite-thumb-rating",{src:"/js/devsite_devsite_thumb_rating_module.js"});w.set("devsite-toc",{src:"/js/devsite_devsite_toc_module.js"});w.set("devsite-topic",{src:"/js/devsite_devsite_topic_module.js"});w.set("devsite-tooltip",{src:"/js/devsite_devsite_tooltip_module.js"});w.set("devsite-tracking-question",{src:"/js/devsite_devsite_tracking_question_module.js"});
w.set("devsite-user",{src:"/js/devsite_devsite_user_module.js"});w.set("devsite-var",{src:"/js/devsite_devsite_var_module.js"});w.set("devsite-version-selector",{src:"/js/devsite_devsite_version_selector_module.js"});w.set("devsite-visibility-analytics",{src:"/js/devsite_devsite_visibility_analytics_module.js"});w.set("devsite-vplus",{src:"/js/devsite_devsite_vplus_module.js"});w.set("devsite-wall-acknowledgement",{src:"/js/devsite_devsite_wall_acknowledgement_module.js"});
w.set("devsite-youtube",{src:"/js/devsite_devsite_youtube_module.js"});w.set("google-codelab",{src:"/js/devsite_google_codelab_module.js"});w.set("google-codelab-about",{src:"/js/devsite_google_codelab_about_module.js"});w.set("google-codelab-analytics",{src:"/js/devsite_google_codelab_analytics_module.js"});w.set("google-codelab-step",{src:"/js/devsite_google_codelab_step_module.js"});w.set("google-codelab-survey",{src:"/js/devsite_google_codelab_survey_module.js"});
v("DevsiteAppAuthorizedElements",w);v("DevsiteAppTenantCustomized",!1);var Ca=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Da=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Ea=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};function Fa(a){return Array.prototype.concat.apply([],arguments)}function Ga(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Ha(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Ga(a,c,c+8192));return b};function Ia(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ja(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Ka;function La(a,b){this.g=b===Ma?a:""}f=La.prototype;f.Va=!0;f.za=function(){return this.g.toString()};f.Ua=!0;f.sa=function(){return 1};f.ka=function(a,b){var c=Na.exec(Oa(this).toString()),d=c[3]||"";return Pa(c[1]+Sa("?",c[2]||"",a)+Sa("#",d,b))};function Oa(a){return a instanceof La&&a.constructor===La?a.g:"type_error:TrustedResourceUrl"}var Na=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Ma={};
function Pa(a){if(void 0===Ka){var b=null;var c=u.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:Ba,createScript:Ba,createScriptURL:Ba})}catch(d){u.console&&u.console.error(d.message)}Ka=b}else Ka=b}a=(b=Ka)?b.createScriptURL(a):a;return new La(a,Ma)}
function Sa(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var g=0;g<e.length;g++){var h=e[g];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b};var Ta=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function x(a,b){return-1!=a.indexOf(b)}function Ua(a,b){return a<b?-1:a>b?1:0};var y;a:{var Va=u.navigator;if(Va){var Wa=Va.userAgent;if(Wa){y=Wa;break a}}y=""};var z=0,A=0;function Xa(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;z=b;A=a}function B(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));z=c;A=a}function Ya(a){var b=0>a;a=2*Math.abs(a);Xa(a);a=z;var c=A;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);z=a;A=c}
function Za(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?z=A=0:(A=0,z=2147483648);else if(isNaN(a))A=0,z=2147483647;else if(3.4028234663852886E38<a)A=0,z=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),A=0,z=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;A=0;z=(b<<31|c+127<<23|a)>>>0}}
function $a(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);z=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;A=b+(c<<8)+(d<<16)+(e<<24)>>>0}function ab(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function bb(a){function b(h,k){for(var l=0;8>l&&(1!==h||0<k);l++)k=h*e[l]+k,e[l]=k&255,k>>>=8}function c(){for(var h=0;8>h;h++)e[h]=~e[h]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],g=0;g<a.length;g++)b(10,a.charCodeAt(g)-48);d&&(c(),b(1,1));return Ha(e)};function C(a,b){this.g=a;this.h=b}function cb(a){return new C((a.g>>>1|(a.h&1)<<31)>>>0,a.h>>>1>>>0)}function db(a){return new C(a.g<<1>>>0,(a.h<<1|a.g>>>31)>>>0)}f=C.prototype;f.jb=function(){return!!(this.g&1)};f.add=function(a){return new C((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};f.sub=function(a){return new C((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};
function eb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new C(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.g||0!=b.h;){var c=new C(0,0);b=new C(b.g,b.h);for(var d=new C(10,0),e=new C(1,0);!(d.h&2147483648);)d=db(d),e=db(e);for(;0!=e.g||0!=e.h;)0>=(d.h<b.h||d.h==b.h&&d.g<b.g?-1:d.h==b.h&&d.g==b.g?0:1)&&(c=c.add(e),b=b.sub(d)),d=cb(d),e=cb(e);c=[c,b];b=c[0];a=c[1].g+a}""==a&&(a="0");return a};
function fb(a){for(var b=new C(0,0),c=new C(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.g=parseInt(a[d],10);var e=eb(b.g);b=eb(b.h);b.h=b.g;b.g=0;b=e.add(b).add(c)}return b}f.ab=function(){return new C(this.g,this.h)};function D(a,b){this.g=a;this.h=b}D.prototype.add=function(a){return new D((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};
D.prototype.sub=function(a){return new D((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};D.prototype.i=function(){return new D(this.g,this.h)};D.prototype.toString=function(){var a=0!=(this.h&2147483648),b=new C(this.g,this.h);a&&(b=(new C(0,0)).sub(b));return(a?"-":"")+b.toString()};function gb(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=fb(a);if(null===a)return null;b&&(a=(new C(0,0)).sub(a));return new D(a.g,a.h)};function hb(){this.g=[]}f=hb.prototype;f.length=function(){return this.g.length};function ib(a){var b=a.g;a.g=[];return b}function E(a,b,c){for(;0<c||127<b;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function F(a,b,c){G(a,b);G(a,c)}function jb(a,b,c){ab(b,c,function(d,e){E(a,d>>>0,e>>>0)})}function H(a,b){for(;127<b;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function kb(a,b){if(0<=b)H(a,b);else{for(var c=0;9>c;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}
function lb(a,b){H(a,(b<<1^b>>31)>>>0)}function mb(a,b){$a(bb(b));ab(z,A,function(c,d){E(a,c>>>0,d>>>0)})}f.Wc=function(a){this.g.push(a>>>0&255)};f.Vc=function(a){this.g.push(a>>>0&255);this.g.push(a>>>8&255)};function G(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)}function nb(a,b){Xa(b);G(a,z);G(a,A)}f.Tb=function(a){this.g.push(a>>>0&255)};f.Sb=function(a){this.g.push(a>>>0&255);this.g.push(a>>>8&255)};
function ob(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)}
function pb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)A=0<1/c?0:2147483648,z=0;else if(isNaN(c))A=2147483647,z=4294967295;else if(1.7976931348623157E308<c)A=(b<<31|2146435072)>>>0,z=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),A=(b<<31|c/4294967296)>>>0,z=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);A=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;z=4503599627370496*c>>>0}G(a,z);G(a,A)}
f.mb=function(a){this.g.push.apply(this.g,a)};function qb(a){qb[" "](a);return a}qb[" "]=wa;var rb=x(y,"Opera"),K=x(y,"Trident")||x(y,"MSIE"),sb=x(y,"Edge"),tb=x(y,"Gecko")&&!(x(y.toLowerCase(),"webkit")&&!x(y,"Edge"))&&!(x(y,"Trident")||x(y,"MSIE"))&&!x(y,"Edge"),ub=x(y.toLowerCase(),"webkit")&&!x(y,"Edge"),vb=x(y,"Macintosh");function wb(){var a=u.document;return a?a.documentMode:void 0}var xb;
a:{var yb="",zb=function(){var a=y;if(tb)return/rv:([^\);]+)(\)|;)/.exec(a);if(sb)return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ub)return/WebKit\/(\S+)/.exec(a);if(rb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();zb&&(yb=zb?zb[1]:"");if(K){var Ab=wb();if(null!=Ab&&Ab>parseFloat(yb)){xb=String(Ab);break a}}xb=yb}var Bb=xb,Cb={},Db;if(u.document&&K){var Eb=wb();Db=Eb?Eb:parseInt(Bb,10)||void 0}else Db=void 0;var Fb=Db;var Gb={},Hb=null;function Ib(a,b){void 0===b&&(b=0);Jb();b=Gb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],g=d+1<a.length,h=g?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|l>>6;l&=63;k||(l=64,g||(h=64));c.push(b[m],b[e],b[h]||"",b[l]||"")}return c.join("")}function Kb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):x("=.",a[b-1])&&(c=x("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Lb(a,function(g){d[e++]=g});return d.subarray(0,e)}
function Lb(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),p=Hb[m];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Jb();for(var d=0;;){var e=c(-1),g=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=h&&(b(g<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function Jb(){if(!Hb){Hb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Gb[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===Hb[g]&&(Hb[g]=e)}}}};function Mb(){this.i=[];this.h=0;this.g=new hb;this.j=[]}function Nb(a,b){var c=ib(a.g);a.i.push(c);a.i.push(b);a.h+=c.length+b.length}function L(a,b){M(a,b,2);b=ib(a.g);a.i.push(b);a.h+=b.length;b.push(a.h);return b}function N(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}f=Mb.prototype;f.lb=function(a,b,c){null!=a&&null!=b&&null!=c&&Nb(this,a.subarray(b,c))};f.nb=function(){this.i=[];ib(this.g);this.h=0;this.j=[]};
function Ob(a){for(var b=new Uint8Array(a.h+a.g.length()),c=a.i,d=c.length,e=0,g=0;g<d;g++){var h=c[g];b.set(h,e);e+=h.length}c=ib(a.g);b.set(c,e);a.i=[b];return b}f.ya=function(a){return Ib(Ob(this),a)};f.ea=function(a){this.j.push(L(this,a))};f.la=function(){N(this,this.j.pop())};function M(a,b,c){H(a.g,8*b+c)}
f.Qb=function(a,b,c){switch(a){case 1:null!=c&&(M(this,b,1),pb(this.g,c));break;case 2:null!=c&&(M(this,b,5),a=this.g,Za(c),G(a,z));break;case 3:null!=c&&null!=c&&(M(this,b,0),a=this.g,B(c),E(a,z,A));break;case 4:null!=c&&null!=c&&(M(this,b,0),a=this.g,B(c),E(a,z,A));break;case 5:null!=c&&Pb(this,b,c);break;case 6:null!=c&&(M(this,b,1),nb(this.g,c));break;case 7:null!=c&&(M(this,b,5),G(this.g,c));break;case 8:Qb(this,b,c);break;case 9:O(this,b,c);break;case 12:Rb(this,b,c);break;case 13:null!=c&&
Sb(this,b,c);break;case 14:Tb(this,b,c);break;case 15:null!=c&&(M(this,b,5),ob(this.g,c));break;case 16:null!=c&&(M(this,b,1),a=this.g,B(c),F(a,z,A));break;case 17:null!=c&&null!=c&&(M(this,b,0),lb(this.g,c));break;case 18:null!=c&&null!=c&&(M(this,b,0),a=this.g,Ya(c),E(a,z,A))}};function Sb(a,b,c){null!=c&&(M(a,b,0),H(a.g,c))}function Pb(a,b,c){null!=c&&(M(a,b,0),kb(a.g,c))}f.Uc=function(a,b){null!=b&&null!=b&&(M(this,a,0),mb(this.g,b))};function Qb(a,b,c){null!=c&&(M(a,b,0),a.g.g.push(c?1:0))}
function Tb(a,b,c){null!=c&&(c=parseInt(c,10),M(a,b,0),kb(a.g,c))}
function O(a,b,c){if(null!=c){b=L(a,b);for(var d=a.g,e=0;e<c.length;e++){var g=c.charCodeAt(e);if(128>g)d.g.push(g);else if(2048>g)d.g.push(g>>6|192),d.g.push(g&63|128);else if(65536>g)if(55296<=g&&56319>=g&&e+1<c.length){var h=c.charCodeAt(e+1);56320<=h&&57343>=h&&(g=1024*(g-55296)+h-56320+65536,d.g.push(g>>18|240),d.g.push(g>>12&63|128),d.g.push(g>>6&63|128),d.g.push(g&63|128),e++)}else d.g.push(g>>12|224),d.g.push(g>>6&63|128),d.g.push(g&63|128)}N(a,b)}}
function Rb(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?Kb(c):new Uint8Array(0),M(a,b,2),H(a.g,c.length),Nb(a,c))}f.Ub=function(a,b,c){null!=b&&(a=L(this,a),c(b,this),N(this,a))};f.Vb=function(a,b,c){null!=b&&(M(this,1,3),M(this,2,0),kb(this.g,a),a=L(this,3),c(b,this),N(this,a),M(this,1,4))};f.Rb=function(a,b,c){null!=b&&(M(this,a,3),c(b,this),M(this,a,4))};
f.Cc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Pb(this,a,b[c])};f.Dc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Pb(this,a,parseInt(d,10))}};f.Ec=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.Nc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,1);F(this.g,g,h)}};
f.Oc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,0);E(this.g,g,h)}};f.Pc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,0);jb(this.g,g>>>0,h>>>0)}};f.Fc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=gb(e),M(this,d,0),E(this.g,e.g,e.h))}};f.Qc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Sb(this,a,b[c])};
f.Rc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Sb(this,a,parseInt(d,10))}};f.Sc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.Tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=fb(e),M(this,d,0),E(this.g,e.g,e.h))}};f.Kc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,0),lb(this.g,d))}};
f.Lc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.g;Ya(d);E(e,z,A)}}};f.Mc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,0),mb(this.g,d))}};f.xc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,5),G(this.g,d))}};f.yc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,1),nb(this.g,d))}};
f.zc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=fb(e),M(this,d,1),F(this.g,e.g,e.h))}};f.Hc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,5),ob(this.g,d))}};f.Ic=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,1);var e=this.g;B(d);F(e,z,A)}}};f.Jc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=gb(e),M(this,d,1),F(this.g,e.g,e.h))}};
f.Ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,5);var e=this.g;Za(d);G(e,z)}}};f.vc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,1),pb(this.g,d))}};f.tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Qb(this,a,b[c])};f.wc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Tb(this,a,b[c])};function Ub(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)O(a,b,c[d])}
f.uc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Rb(this,a,b[c])};f.Gc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=L(this,a);c(b[d],this);N(this,e)}};f.Bc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)M(this,a,3),c(b[d],this),M(this,a,4)};f.bc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)kb(this.g,b[c]);N(this,a)}};f.cc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)kb(this.g,parseInt(b[c],10));N(this,a)}};
f.dc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}N(this,a)}};f.mc=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=0;e<b.length;e++)F(this.g,c(b[e]),d(b[e]));N(this,a)}};f.nc=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=0;e<b.length;e++)E(this.g,c(b[e]),d(b[e]));N(this,a)}};f.oc=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=this.g,g=0;g<b.length;g++)jb(e,c(b[g]),d(b[g]));N(this,a)}};
f.ec=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=gb(b[c]);E(this.g,d.g,d.h)}N(this,a)}};f.pc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)H(this.g,b[c]);N(this,a)}};f.qc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)H(this.g,parseInt(b[c],10));N(this,a)}};f.rc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}N(this,a)}};
f.sc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=fb(b[c]);E(this.g,d.g,d.h)}N(this,a)}};f.jc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)lb(this.g,b[c]);N(this,a)}};f.kc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.g;Ya(b[c]);E(d,z,A)}N(this,a)}};f.lc=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)mb(this.g,b[c]);N(this,a)}};
f.Yb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)G(this.g,b[a])};f.Zb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)nb(this.g,b[a])};f.$b=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=fb(b[a]);F(this.g,c.g,c.h)}};f.fc=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)ob(this.g,b[a])};
f.hc=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;B(b[a]);F(c,z,A)}};f.ic=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;$a(bb(b[a]));F(c,z,A)}};f.ac=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++){var c=this.g;Za(b[a]);G(c,z)}};f.Xb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)pb(this.g,b[a])};
f.Wb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),H(this.g,b.length),a=0;a<b.length;a++)this.g.g.push(b[a]?1:0)};function Vb(){}var Wb="function"==typeof Uint8Array;Vb.prototype.s=function(){return this.m};var Xb=[];function Yb(a){var b=a.j+a.l;a.g[b]||(a.h=a.g[b]={})}function P(a,b){if(b<a.j){b+=a.l;var c=a.g[b];return c!==Xb?c:a.g[b]=[]}if(a.h)return c=a.h[b],c===Xb?a.h[b]=[]:c}function Zb(a,b,c){a=P(a,b);return null==a?c:a}function Q(a,b){return Zb(a,b,"")}function R(a,b){var c=void 0===c?!1:c;a=P(a,b);a=null==a?a:!!a;return null==a?c:a}function S(a,b,c){b<a.j?a.g[b+a.l]=c:(Yb(a),a.h[b]=c);return a}
function U(a,b,c,d){c!==d?S(a,b,c):b<a.j?a.g[b+a.l]=null:(Yb(a),delete a.h[b]);return a}function $b(a,b,c,d){b=P(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}f=Vb.prototype;f.Kb=function(){if(this.i)for(var a in this.i){var b=this.i[a];if(Array.isArray(b))for(var c=0;c<b.length;c++);}};f.Nb=function(){return this.g};
f.V=Wb?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return Ib(this)};try{return JSON.stringify(this.g&&this.g,ac)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.g&&this.g,ac)};function ac(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}f.toString=function(){return this.g.toString()};
f.pb=function(a){Yb(this);this.i||(this.i={});var b=a.i;return a.j?a.g()?(this.i[b]||(this.i[b]=Ea(this.h[b]||[],function(c){return new a.h(c)})),this.i[b]):this.h[b]=this.h[b]||[]:a.g()?(!this.i[b]&&this.h[b]&&(this.i[b]=new a.h(this.h[b])),this.i[b]):this.h[b]};f.vb=function(a,b){this.i||(this.i={});Yb(this);var c=a.i;a.j?(b=b||[],a.g()?(this.i[c]=b,this.h[c]=Ea(b,function(d){return d.g})):this.h[c]=b):a.g()?(this.i[c]=b,this.h[c]=b?b.g:b):this.h[c]=b;return this};f.ja=function(){return new this.constructor(bc(this.g))};
f.ob=function(){return new this.constructor(bc(this.g))};function bc(a){if(Array.isArray(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?bc(d):d)}return b}if(Wb&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?bc(d):d);return b};function cc(a){var b=a;a=dc;this.i=null;b||(b=[]);this.m=void 0;this.l=-1;this.g=b;a:{if(b=this.g.length){--b;var c=this.g[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||Wb&&c instanceof Uint8Array)){this.j=b- -1;this.h=c;break a}}this.j=Number.MAX_VALUE}this.o={};if(a)for(b=0;b<a.length;b++)c=a[b],c<this.j?(c+=-1,this.g[c]=this.g[c]||Xb):(Yb(this),this.h[c]=this.h[c]||Xb)}Aa(cc,Vb);var dc=[10,12,13];f=cc.prototype;
f.qb=function(a){var b,c={Lb:Zb(this,1,0),locale:Q(this,2),ca:Q(this,4),Ba:Q(this,5),Mb:Q(this,6),Wa:Q(this,7),Ya:R(this,8),Xa:R(this,9),fa:null==(b=P(this,10))?void 0:b,Za:R(this,11),Jb:null==(b=P(this,12))?void 0:b,oa:null==(b=P(this,13))?void 0:b};a&&(c.Z=this);return c};
f.sb=function(){var a=new Mb;var b=this.getTenantId();0!==b&&Tb(a,1,b);b=this.getLocale();0<b.length&&O(a,2,b);b=Q(this,4);0<b.length&&O(a,4,b);b=Q(this,5);0<b.length&&O(a,5,b);b=Q(this,6);0<b.length&&O(a,6,b);b=this.getInsecureHost();0<b.length&&O(a,7,b);(b=R(this,8))&&Qb(a,8,b);(b=R(this,9))&&Qb(a,9,b);b=P(this,10);0<b.length&&Ub(a,10,b);(b=R(this,11))&&Qb(a,11,b);b=P(this,12);0<b.length&&Ub(a,12,b);b=P(this,13);if(0<b.length&&null!=b&&b.length){for(var c=L(a,13),d=0;d<b.length;d++)kb(a.g,b[d]);
N(a,c)}return Ob(a)};f.getTenantId=function(){return Zb(this,1,0)};f.Hb=function(a){return U(this,1,a,0)};f.getLocale=function(){return Q(this,2)};f.tb=function(a){return U(this,4,a,"")};f.yb=function(a){return U(this,5,a,"")};f.Ib=function(a){return U(this,6,a,"")};f.getInsecureHost=function(){return Q(this,7)};f.zb=function(a){return U(this,7,a,"")};f.Bb=function(a){return U(this,8,a,!1)};f.Ab=function(a){return U(this,9,a,!1)};f.ub=function(a){return S(this,10,a||[])};
f.$=function(a,b){return $b(this,10,a,b)};f.ga=function(){return S(this,10,[])};f.Cb=function(a){return U(this,11,a,!1)};f.Gb=function(a){return S(this,12,a||[])};f.ba=function(a,b){return $b(this,12,a,b)};f.ia=function(){return S(this,12,[])};f.wb=function(a){return S(this,13,a||[])};f.aa=function(a,b){return $b(this,13,a,b)};f.ha=function(){return S(this,13,[])};function ec(){var a=GoogleDevelopersObject;return new cc(a?JSON.parse(a):null)};var fc="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""};function gc(){}gc.prototype.next=function(){throw fc;};gc.prototype.g=function(){return this};function hc(a,b){this.h={};this.g=[];this.j=this.i=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof hc)for(c=a.B(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=hc.prototype;f.v=function(){ic(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};f.B=function(){ic(this);return this.g.concat()};
f.Qa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if(V(this.h,c)&&this.h[c]==a)return!0}return!1};f.na=function(a,b){if(this===a)return!0;if(this.i!=a.i)return!1;b=b||jc;ic(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function jc(a,b){return a===b}f.Ra=function(){return 0==this.i};f.Pa=function(){this.h={};this.j=this.i=this.g.length=0};
function ic(a){if(a.i!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];V(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.i!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],V(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}f.get=function(a,b){return V(this.h,a)?this.h[a]:b};f.set=function(a,b){V(this.h,a)||(this.i++,this.g.push(a),this.j++);this.h[a]=b};f.forEach=function(a,b){for(var c=this.B(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
f.Ob=function(){for(var a=new hc,b=0;b<this.g.length;b++){var c=this.g[b];a.set(this.h[c],c)}return a};f.Sa=function(){ic(this);for(var a={},b=0;b<this.g.length;b++){var c=this.g[b];a[c]=this.h[c]}return a};f.ua=function(){return kc(this,!0)};f.Aa=function(){return kc(this,!1)};function kc(a,b){ic(a);var c=0,d=a.j,e=new gc;e.next=function(){if(d!=a.j)throw Error("The map has changed since the iterator was created");if(c>=a.g.length)throw fc;var g=a.g[c++];return b?g:a.h[g]};return e}
function V(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function lc(a){if(a.v&&"function"==typeof a.v)return a.v();if("string"===typeof a)return a.split("");if(xa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function mc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(xa(a)||"string"===typeof a)Da(a,b,c);else{if(a.B&&"function"==typeof a.B)var d=a.B();else if(a.v&&"function"==typeof a.v)d=void 0;else if(xa(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=lc(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var nc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function oc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function pc(a,b){this.h=this.s=this.m="";this.j=null;this.o=this.i="";this.l=this.D=!1;if(a instanceof pc){this.l=void 0!==b?b:a.l;qc(this,a.m);var c=a.s;W(this);this.s=c;c=a.h;W(this);this.h=c;rc(this,a.j);c=a.i;W(this);this.i=c;sc(this,tc(a.g));a=a.o;W(this);this.o=a}else a&&(c=String(a).match(nc))?(this.l=!!b,qc(this,c[1]||"",!0),a=c[2]||"",W(this),this.s=uc(a),a=c[3]||"",W(this),this.h=uc(a,!0),rc(this,c[4]),a=c[5]||"",W(this),this.i=uc(a,!0),sc(this,c[6]||"",!0),a=c[7]||"",W(this),this.o=uc(a)):
(this.l=!!b,this.g=new vc(null,this.l))}f=pc.prototype;f.toString=function(){var a=[],b=this.m;b&&a.push(wc(b,xc,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(wc(b,xc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.i)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(wc(c,"/"==c.charAt(0)?yc:zc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.o)&&a.push("#",wc(c,Ac));return a.join("")};
f.resolve=function(a){var b=new pc(this),c=!!a.m;c?qc(b,a.m):c=!!a.s;if(c){var d=a.s;W(b);b.s=d}else c=!!a.h;c?(d=a.h,W(b),b.h=d):c=null!=a.j;d=a.i;if(c)rc(b,a.j);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.h&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(x(e,"./")||x(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&
""!=g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(W(b),b.i=d):c=""!==a.g.toString();c?sc(b,tc(a.g)):c=!!a.o;c&&(a=a.o,W(b),b.o=a);return b};function qc(a,b,c){W(a);a.m=c?uc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))}function rc(a,b){W(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null}function sc(a,b,c){W(a);b instanceof vc?(a.g=b,Bc(a.g,a.l)):(c||(b=wc(b,Cc)),a.g=new vc(b,a.l));return a}
f.Eb=function(a,b){return sc(this,a,b)};f.ra=function(){return uc(this.g.toString())};f.Ha=function(){return this.g.toString()};f.Db=function(a,b){W(this);Array.isArray(b)||(b=[String(b)]);Dc(this.g,a,b);return this};f.xa=function(a){return this.g.v(a)};f.wa=function(a){return this.g.get(a)};f.Ta=function(a){return(!this.h&&!a.h||this.h==a.h)&&(null==this.j&&null==a.j||this.j==a.j)};
f.kb=function(){W(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36);W(this);this.g.set("zx",a);return this};f.Ia=function(a){W(this);Ec(this.g,a);return this};f.Fb=function(a){this.D=a;return this};f.$a=function(){return this.D};function W(a){if(a.D)throw Error("Tried to modify a read-only Uri");}f.Ja=function(a){this.l=a;this.g&&Bc(this.g,a);return this};
function Fc(a){return a instanceof pc?new pc(a):new pc(a,void 0)}function uc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function wc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Gc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Gc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var xc=/[#\/\?@]/g,zc=/[#\?:]/g,yc=/[#\?]/g,Cc=/[#\?@]/g,Ac=/#/g;function vc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function X(a){a.g||(a.g=new hc,a.h=0,a.i&&oc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=vc.prototype;f.Fa=function(){X(this);return this.h};f.add=function(a,b){X(this);this.i=null;a=Hc(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Ec(a,b){X(a);b=Hc(a,b);V(a.g.h,b)&&(a.i=null,a.h-=a.g.get(b).length,a=a.g,V(a.h,b)&&(delete a.h[b],a.i--,a.j++,a.g.length>2*a.i&&ic(a)))}f.Ca=function(){this.g=this.i=null;this.h=0};
f.Ga=function(){X(this);return 0==this.h};function Ic(a,b){X(a);b=Hc(a,b);return V(a.g.h,b)}f.Da=function(a){var b=this.v();return 0<=Ca(b,a)};f.forEach=function(a,b){X(this);this.g.forEach(function(c,d){Da(c,function(e){a.call(b,e,d,this)},this)},this)};f.B=function(){X(this);for(var a=this.g.v(),b=this.g.B(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
f.v=function(a){X(this);var b=[];if("string"===typeof a)Ic(this,a)&&(b=Fa(b,this.g.get(Hc(this,a))));else{a=this.g.v();for(var c=0;c<a.length;c++)b=Fa(b,a[c])}return b};f.set=function(a,b){X(this);this.i=null;a=Hc(this,a);Ic(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};f.get=function(a,b){if(!a)return b;a=this.v(a);return 0<a.length?String(a[0]):b};
function Dc(a,b,c){Ec(a,b);if(0<c.length){a.i=null;var d=a.g,e=d.set;b=Hc(a,b);var g=c.length;if(0<g){for(var h=Array(g),k=0;k<g;k++)h[k]=c[k];g=h}else g=[];e.call(d,b,g);a.h+=c.length}}f.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=this.g.B(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.v(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.i=a.join("&")};
f.pa=function(a){X(this);this.g.forEach(function(b,c){0<=Ca(a,c)||Ec(this,c)},this);return this};function tc(a){var b=new vc;b.i=a.i;a.g&&(b.g=new hc(a.g),b.h=a.h);return b}function Hc(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Bc(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Ec(this,d),Dc(this,e,c))},a));a.j=b}f.Ea=function(a){for(var b=0;b<arguments.length;b++)mc(arguments[b],function(c,d){this.add(d,c)},this)};var Jc={};function Kc(a,b){var c=Jc[a];if(void 0!==c&&(!c.O||Date.now()<=c.O+3E5))return c.p;c=new Promise(function(e,g){b.onload=function(){return e(b)};b.onerror=function(h){b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});var d={O:0,p:c};c.catch(function(){return d.O=+new Date});Jc[a]=d;return c}
function Lc(a){var b=void 0===b?null:b;a=Fc(a);var c=document.createElement("script");var d=Pa(a.toString());c.src=Oa(d);(d=c.ownerDocument&&c.ownerDocument.defaultView)&&d!=u?d=va(d.document):(null===ua&&(ua=va(u.document)),d=ua);d&&c.setAttribute("nonce",d);b&&(c.type=b);return Kc(a.toString(),c)};var Mc=!K||9<=Number(Fb),Nc=!K||9<=Number(Fb),Oc;
if(Oc=K){var Pc;if(Object.prototype.hasOwnProperty.call(Cb,"9"))Pc=Cb["9"];else{for(var Qc=0,Rc=Ta(String(Bb)).split("."),Sc=Ta("9").split("."),Tc=Math.max(Rc.length,Sc.length),Uc=0;0==Qc&&Uc<Tc;Uc++){var Vc=Rc[Uc]||"",Wc=Sc[Uc]||"";do{var Xc=/(\d*)(\D*)(.*)/.exec(Vc)||["","","",""],Yc=/(\d*)(\D*)(.*)/.exec(Wc)||["","","",""];if(0==Xc[0].length&&0==Yc[0].length)break;Qc=Ua(0==Xc[1].length?0:parseInt(Xc[1],10),0==Yc[1].length?0:parseInt(Yc[1],10))||Ua(0==Xc[2].length,0==Yc[2].length)||Ua(Xc[2],Yc[2]);
Vc=Xc[3];Wc=Yc[3]}while(0==Qc)}Pc=Cb["9"]=0<=Qc}Oc=!Pc}var Zc=Oc,$c=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",wa,b),u.removeEventListener("test",wa,b)}catch(c){}return a}();function ad(){this.F=this.F;this.h=this.h}f=ad.prototype;f.F=!1;f.Y=function(){return this.F};f.ta=ad.prototype.Y;f.M=function(){this.F||(this.F=!0,this.N())};f.rb=function(a){a=za(bd,a);this.F?a():(this.h||(this.h=[]),this.h.push(a))};f.N=function(){if(this.h)for(;this.h.length;)this.h.shift()()};function bd(a){a&&"function"==typeof a.M&&a.M()};function cd(a,b){this.type=a;this.h=this.target=b;this.J=this.j=!1}cd.prototype.l=function(){this.j=!0};cd.prototype.i=function(){this.J=!0};function Y(a,b){cd.call(this,a?a.type:"");this.relatedTarget=this.h=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.D=this.s=0;this.key="";this.m=this.o=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.R=null;this.K=!1;this.pointerId=0;this.pointerType="";this.g=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.h=b;if(b=a.relatedTarget){if(tb){a:{try{qb(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.s=ub||void 0!==a.offsetX?a.offsetX:a.layerX,this.D=ub||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.o=a.keyCode||0;this.key=a.key||"";this.m=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.K=vb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:dd[a.pointerType]||"";this.R=a.state;this.g=a;a.defaultPrevented&&this.i()}}Aa(Y,cd);var ed=[1,4,2],dd={2:"touch",3:"pen",4:"mouse"};
Y.prototype.S=function(){return(Mc?0==this.g.button:"click"==this.type?!0:!!(this.g.button&ed[0]))&&!(vb&&this.ctrlKey)};Y.prototype.l=function(){Y.P.l.call(this);this.g.stopPropagation?this.g.stopPropagation():this.g.cancelBubble=!0};Y.prototype.i=function(){Y.P.i.call(this);var a=this.g;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Zc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var fd="closure_listenable_"+(1E6*Math.random()|0),gd=0;function hd(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.h=e;this.key=++gd;this.G=this.L=!1}function id(a){a.G=!0;a.listener=null;a.g=null;a.src=null;a.h=null};function jd(a){this.src=a;this.g={};this.h=0}f=jd.prototype;f.La=function(){var a=0,b;for(b in this.g)a+=this.g[b].length;return a};f.add=function(a,b,c,d,e){var g=a.toString();a=this.g[g];a||(a=this.g[g]=[],this.h++);var h=kd(a,b,d,e);-1<h?(b=a[h],c||(b.L=!1)):(b=new hd(b,this.src,g,!!d,e),b.L=c,a.push(b));return b};
f.Na=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=kd(e,b,c,d);return-1<b?(id(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};f.Oa=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,id(d[e]);delete this.g[c];this.h--}return b};f.va=function(a,b){a=this.g[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.Ma=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ja(this.g,function(g){for(var h=0;h<g.length;++h)if(!(c&&g[h].type!=d||e&&g[h].capture!=b))return!0;return!1})};function kd(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.G&&g.listener==b&&g.capture==!!c&&g.h==d)return e}return-1};var ld="closure_lm_"+(1E6*Math.random()|0),md={},nd=0;function od(a,b,c,d,e){if(d&&d.once)return pd(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)od(a,b[g],c,d,e);return null}c=qd(c);return a&&a[fd]?a.h(b,c,ya(d)?!!d.capture:!!d,e):rd(a,b,c,!1,d,e)}
function rd(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=ya(e)?!!e.capture:!!e,k=sd(a);k||(a[ld]=k=new jd(a));c=k.add(b,c,d,h,g);if(c.g)return c;d=td();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)$c||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(ud(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");nd++;return c}
function td(){var a=vd,b=Nc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function pd(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)pd(a,b[g],c,d,e);return null}c=qd(c);return a&&a[fd]?a.i(b,c,ya(d)?!!d.capture:!!d,e):rd(a,b,c,!0,d,e)}
function wd(a){if("number"!==typeof a&&a&&!a.G){var b=a.src;if(b&&b[fd])b.j(a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ud(c),d):b.addListener&&b.removeListener&&b.removeListener(d);nd--;if(c=sd(b)){d=a.type;if(d in c.g){var e=c.g[d],g=Ca(e,a),h;(h=0<=g)&&Array.prototype.splice.call(e,g,1);h&&(id(a),0==c.g[d].length&&(delete c.g[d],c.h--))}0==c.h&&(c.src=null,b[ld]=null)}else id(a)}}}
function ud(a){return a in md?md[a]:md[a]="on"+a}function xd(a,b,c,d){var e=!0;if(a=sd(a))if(b=a.g[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.G&&(g=yd(g,d),e=e&&!1!==g)}return e}function yd(a,b){var c=a.listener,d=a.h||a.src;a.L&&wd(a);return c.call(d,b)}
function vd(a,b){if(a.G)return!0;if(!Nc){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Y(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.h;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.j&&0<=e;e--){b.h=d[e];var g=xd(d[e],a,!0,b);c=c&&g}for(e=0;!b.j&&e<d.length;e++)b.h=d[e],g=xd(d[e],a,!1,b),c=
c&&g}return c}return yd(a,new Y(b,this))}function sd(a){a=a[ld];return a instanceof jd?a:null}var zd="__closure_events_fn_"+(1E9*Math.random()>>>0);function qd(a){if("function"===typeof a)return a;a[zd]||(a[zd]=function(b){return a.handleEvent(b)});return a[zd]};function Ad(a){ad.call(this);this.i=a;this.g={}}Aa(Ad,ad);var Bd=[];f=Ad.prototype;f.gb=function(a,b,c,d,e){return Cd(this,a,b,c,d,e)};function Cd(a,b,c,d,e,g){Array.isArray(c)||(c&&(Bd[0]=c.toString()),c=Bd);for(var h=0;h<c.length;h++){var k=od(b,c[h],d||a.handleEvent,e||!1,g||a.i||a);if(!k)break;a.g[k.key]=k}return a}function Dd(a,b){Ed(Z.h,a,"devsite-content-updated",b,void 0)}f.fb=function(a,b,c,d,e){return Ed(this,a,b,c,d,e)};
function Ed(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)Ed(a,b,c[h],d,e,g);else{b=pd(b,c,d||a.handleEvent,e,g||a.i||a);if(!b)return a;a.g[b.key]=b}return a}f.hb=function(a,b,c,d){b.g(a,c,d,this.i||this,this);return this};f.ib=function(a,b,c,d,e){b.g(a,c,d,e||this.i||this,this);return this};f.Ka=function(){var a=0,b;for(b in this.g)Object.prototype.hasOwnProperty.call(this.g,b)&&a++;return a};
function Fd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)Fd(a,b,c[h],d,e,g);else d=d||a.handleEvent,e=ya(e)?!!e.capture:!!e,g=g||a.i||a,d=qd(d),e=!!e,b&&b[fd]?c=b.g(c,d,e,g):b?(b=sd(b))?(c=b.g[c.toString()],b=-1,c&&(b=kd(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(wd(c),delete a.g[c.key])}f.Pb=function(a,b,c,d,e){b.h(a,c,d,e||this.i||this,this);return this};function Gd(a){Ia(a.g,function(b,c){this.g.hasOwnProperty(c)&&wd(b)},a);a.g={}}f.N=function(){Ad.P.N.call(this);Gd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Hd(){var a=this;if(u.__globalAppLoader)return u.__globalAppLoader;this.i=null;this.m=!1;this.h=new Ad;this.j=[];this.l=function(b){a.j.push(b)};try{this.g=ec()}catch(b){Id("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;v("__globalAppLoader",this)}Hd.prototype.M=function(){Gd(this.h)};
function Jd(a){var b=[];b.push(Lc("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Lc(Q(a.g,5)+"/js/polyfills.js"));return Promise.all(b)}
function Kd(){var a=Ld,b,c,d,e,g,h,k;return sa(new ra(new na(function(l){switch(l.g){case 1:return K&&document.body.setAttribute("ie-"+parseInt(Bb,10),""),l.i=2,r(l,Jd(a),4);case 4:ka(l,3);break;case 2:b=la(l),Id("Failed to load Devsite App dependencies: "+b.message);case 3:c=new Promise(function(m){v("__devsiteAppReadyResolver",m)});v("__devsiteAppReadyPromise",c);v("DevsiteApp.whenReady",function(){return c});if(!P(a.g,12).length){l.C(5);break}l.i=6;return r(l,Promise.all(P(a.g,12).map(function(m){m=
Fc(m);var p=document.createElement("link");p.setAttribute("rel","stylesheet");p.setAttribute("type","text/css");p.setAttribute("href",m.toString());return Kc(m.toString(),p)})),8);case 8:ka(l,5);break;case 6:d=la(l),Id("Failed to load Devsite App dependencies: "+d.message);case 5:return e=u.DevsiteAppTenantCustomized?Q(a.g,6):Q(a.g,5),l.i=9,r(l,Lc(e+(a.g.getLocale()&&"en"!=a.g.getLocale()?Q(a.g,4).replace(/\.js$/,"__"+a.g.getLocale().toLowerCase().replace("-","_")+".js"):Q(a.g,4))),11);case 11:ka(l,
10);break;case 9:g=la(l);if("en"===a.g.getLocale()){Id("Failed to load Devsite App binary: "+g.message);l.C(10);break}U(a.g,2,"en","");l.i=13;return r(l,Lc(e+Q(a.g,4)),15);case 15:ka(l,10);break;case 13:h=la(l),Id("Failed to load Devsite App binary: "+h.message);case 10:if(k=document,"complete"===k.readyState||"interactive"===k.readyState)l.C(0);else return r(l,new Promise(function(m){k.addEventListener("readystatechange",function(){"interactive"!==k.readyState&&"complete"!==k.readyState||m()})}),
0)}})))}function Id(a){throw new function(b){this.message=b;this.name="DevsiteAppLoaderException"}(void 0===a?"Devsite has failed to load.":a);};var Z=new Hd;(function(){var a=document.querySelector("devsite-content");a&&(Cd(Z.h,window,"message",Z.l,void 0),Dd(a,function(){Fd(Z.h,window,"message",Z.l);for(var b=q(Z.j),c=b.next();!c.done;c=b.next())window.dispatchEvent(c.value.g);Z.j=[]}))})();var Md;var Ld=Z;"WeakMap"in window&&"performance"in window&&"now"in window.performance?(Ld.i||(Ld.i=Kd()),Md=Ld.i):Md=Promise.resolve();
Md.then(function(){u.DevsiteAppInit||Id("Failed to load Devsite App binary");R(Z.g,9)?DevsiteAppFrameboxInit(Z.g.V(),u.DevsiteAppAuthorizedElements):DevsiteAppInit(Z.g.V(),u.DevsiteAppAuthorizedElements)});}).call(this);
